export const menu = [
    {
        id: 1,
        title: 'buttermilk pancakes',
        category: 'breakfast',
        price: 15.59,
        img:'./images/item-1.jpeg',
        remote_img: '',
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Nobis, corporis.',
    },
    {
        id: 2,
        title: 'dinner double',
        category: 'dinner',
        price: 15.59,
        img:'./images/item-2.jpeg',
        remote_img: '',
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Nobis, corporis.',
    },
    {
        id: 3,
        title: 'godzilla milkshake',
        category: 'shakes',
        price: 15.59,
        img:'./images/item-3.jpeg',
        remote_img: '',
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Nobis, corporis.',
    },
    {
        id: 4,
        title: 'muffin blueberry',
        category: 'breakfast',
        price: 15.59,
        img:'./images/my-1.jpg',
        remote_img: '',
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Nobis, corporis.',
    },
    {
        id: 5,
        title: 'Tomato Pasta',
        category: 'lunch',
        price: 15.59,
        img:'./images/my-2.jpg',
        remote_img: '',
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Nobis, corporis.',
    },
    {
        id: 6,
        title: 'steak',
        category: 'dinner',
        price: 15.59,
        img:'./images/my-3.jpg',
        remote_img: '',
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Nobis, corporis.',
    }
]

